# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb22134b53c9300fc5c04bbbc285a650a398372381a26e6cc0bd97e950556dbea2b0c7fbaa9c9a1bd9b587764fcdcaa2310a5746f8a9b7cf40e988fd7a0dbbb1

test:
  secret_key_base: 14083021717c334727e881efc175929ecd551f2b196fb8a9a12608627c0aff754ac16803e7a3f883f5b7476125274adfb2f27e54b64b7ba0a514f15924ff75d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
